function sqlTypeToPrisma(sqlType: string): string {
    const typeMap: Record<string, string> = {
        int:"Int",
        integer:"Int",
        varchar:"String",
        text:"String",
        string:"String",
        boolean:"Boolean",
        bool:"Boolean",
        float:"Float",
        double:"Float",
        decimal:"Float",
        datetime:"DateTime",
        date:"DateTime",
        timestamp:"DateTime",
    };
    return typeMap[sqlType.toLowerCase()] || "String"; 
    }

    
function toModelName(tableName: string): string {
    return tableName.charAt(0).toUpperCase() + tableName.slice(1).toLowerCase();
}

export function generatePrismaSchema(dbSchema: any): string {
  let schema = `// Generated by AppCompiler
datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

generator client {
  provider = "prisma-client-js"
}

`;

  for (const table of dbSchema.tables) {
    const modelName = toModelName(table.name);
    schema += `model ${modelName} {\n`;

    for (const column of table.columns) {
      const prismaType = sqlTypeToPrisma(column.type);
      const isPrimaryKey = column.primary_key;

      if (isPrimaryKey) {
        schema += `  ${column.name}  ${prismaType}  @id @default(autoincrement())\n`;
      } else {
        schema += `  ${column.name}  ${prismaType}\n`;
      }
    }

    schema += `}\n\n`;
  }

  return schema;
}    